version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    command: 
      - start-dev
      - --hostname-strict=false
      - --hostname=localhost
      - --spi-cors-default-allowed-origins=http://localhost:5173,http://localhost:3000

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

